# Generated by Django 5.0.7 on 2024-07-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(default='USER', max_length=50),
        ),
    ]
